/**
 * @fileoverview The Writing Generator for the Castle Factory.
 * Focuses on generating documentation, summaries, and structured content.
 * Aligns with Clarity rsis808 principle.
 */

import { Generator, GenerationResult } from '../registry';
import { FactoryTask } from '../../src/core/gatekeeper';
import { LogicDecision } from '../../src/core/logic';

const writingGenerator: Generator = {
    name: 'writing',
    description: 'Generates documentation, summaries, and structured content.',
    execute: async (task: FactoryTask, decision: LogicDecision): Promise<GenerationResult> => {
        // --- Functional Logic Implementation ---
        
        const title = task.request.length > 50 ? task.request.substring(0, 50) + '...' : task.request;
        
        const generatedDoc = `# Generated Document: ${title}

## Request Analysis
*   **Source Request:** \`${task.request}\`
*   **Logic Decision:** \`${decision.reason}\`
*   **Generator Used:** \`${writingGenerator.name}\`

## Structured Content (Clarity Principle)

This document is generated to be clear, concise, and structured.

### 1. Purpose
The purpose of this content is to address the user's request by providing a well-organized summary or document.

### 2. Key Takeaways
- The Castle ensures all content adheres to the **Security-First** principle.
- The output is designed for **Clarity** and **Simplicity**.
- The operator maintains **Local Control** over this document.

### 3. Next Steps
Review this document for accuracy and completeness. You can use this as a foundation for your final documentation.

---
*Generated by hubhomie-cogpt, a product of the Castle Software Factory.*
`;

        return {
            success: true,
            output: 'Structured documentation generated successfully.',
            files: {
                'docs/generated/structured_doc.md': generatedDoc,
            },
        };
    },
};

export { writingGenerator };
